language: python
python:
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
install:
    - "pip install flake8"
    - "pip install ."
script:
    - "python -m test.test_facebook"
    - "flake8 --ignore=E402,F401 examples"
    - "flake8 facebook"
    - "flake8 test"
env:
    global:
        - FACEBOOK_APP_ID=198798870326423
        - FACEBOOK_SECRET=2db4d76fe8a336cf292470c20a5a5684
